#pragma once

#pragma comment(linker, "/export:ApplyCompatResolutionQuirking=C:\\WINDOWS\\System32\\dxgi.ApplyCompatResolutionQuirking,@1")
#pragma comment(linker, "/export:CompatString=C:\\WINDOWS\\System32\\dxgi.CompatString,@2")
#pragma comment(linker, "/export:CompatValue=C:\\WINDOWS\\System32\\dxgi.CompatValue,@3")
#pragma comment(linker, "/export:CreateDXGIFactory=C:\\WINDOWS\\System32\\dxgi.CreateDXGIFactory,@10")
#pragma comment(linker, "/export:CreateDXGIFactory1=C:\\WINDOWS\\System32\\dxgi.CreateDXGIFactory1,@11")
#pragma comment(linker, "/export:CreateDXGIFactory2=C:\\WINDOWS\\System32\\dxgi.CreateDXGIFactory2,@12")
#pragma comment(linker, "/export:DXGID3D10CreateDevice=C:\\WINDOWS\\System32\\dxgi.DXGID3D10CreateDevice,@13")
#pragma comment(linker, "/export:DXGID3D10CreateLayeredDevice=C:\\WINDOWS\\System32\\dxgi.DXGID3D10CreateLayeredDevice,@14")
#pragma comment(linker, "/export:DXGID3D10GetLayeredDeviceSize=C:\\WINDOWS\\System32\\dxgi.DXGID3D10GetLayeredDeviceSize,@15")
#pragma comment(linker, "/export:DXGID3D10RegisterLayers=C:\\WINDOWS\\System32\\dxgi.DXGID3D10RegisterLayers,@16")
#pragma comment(linker, "/export:DXGIDeclareAdapterRemovalSupport=C:\\WINDOWS\\System32\\dxgi.DXGIDeclareAdapterRemovalSupport,@17")
#pragma comment(linker, "/export:DXGIDumpJournal=C:\\WINDOWS\\System32\\dxgi.DXGIDumpJournal,@4")
#pragma comment(linker, "/export:DXGIGetDebugInterface1=C:\\WINDOWS\\System32\\dxgi.DXGIGetDebugInterface1,@18")
#pragma comment(linker, "/export:DXGIReportAdapterConfiguration=C:\\WINDOWS\\System32\\dxgi.DXGIReportAdapterConfiguration,@19")
#pragma comment(linker, "/export:PIXBeginCapture=C:\\WINDOWS\\System32\\dxgi.PIXBeginCapture,@5")
#pragma comment(linker, "/export:PIXEndCapture=C:\\WINDOWS\\System32\\dxgi.PIXEndCapture,@6")
#pragma comment(linker, "/export:PIXGetCaptureState=C:\\WINDOWS\\System32\\dxgi.PIXGetCaptureState,@7")
#pragma comment(linker, "/export:SetAppCompatStringPointer=C:\\WINDOWS\\System32\\dxgi.SetAppCompatStringPointer,@8")
#pragma comment(linker, "/export:UpdateHMDEmulationStatus=C:\\WINDOWS\\System32\\dxgi.UpdateHMDEmulationStatus,@9")
